<?php

declare(strict_types=1);

namespace App\Command\CreateCompetition;

use App\Enum\CompetitionMatchSelectionMode;
use App\Enum\CompetitionMonetization;
use App\Value\CompetitionSourceSpec;
use Symfony\Component\Uid\Uuid;

/**
 * Single command behind the create-competition wizard (S08). Composes the whole
 * aggregate in ONE transaction: an optional from-scratch private source, the
 * competition + owner membership, match selection rows, per-rule configuration
 * and invitations.
 *
 * Source is XOR: either an existing `$matchSourceId` (curated or the manager's
 * own private source) OR `$fromScratch = true` with a `$sportId` (a hidden
 * private source is created). That pair describes the soutěž's FIRST scope
 * layer; `$additionalSources` carries every further zdroj it draws from, each
 * with its own selection mode. All layers must share one sport.
 */
final readonly class CreateCompetitionCommand
{
    /**
     * @param list<Uuid>                                       $selectedMatchIds  only used when $selectionMode is Subset
     * @param list<Uuid>                                       $filterTeamIds     only used when $selectionMode is Teams
     * @param list<CompetitionSourceSpec>                      $additionalSources further zdroje the soutěž draws from, after the first
     * @param array<string, array{enabled: bool, points: int}> $ruleChanges       rule identifier → desired state (over the defaults)
     * @param list<string>                                     $inviteEmails      raw e-mail entries (validated in the handler)
     */
    public function __construct(
        public Uuid $ownerId,
        public string $name,
        public ?Uuid $matchSourceId,
        public ?Uuid $sportId,
        public bool $fromScratch,
        public bool $withPin,
        public CompetitionMonetization $monetization = CompetitionMonetization::Boosts,
        public CompetitionMatchSelectionMode $selectionMode = CompetitionMatchSelectionMode::All,
        public bool $includePlayoff = true,
        public array $selectedMatchIds = [],
        public array $filterTeamIds = [],
        public array $additionalSources = [],
        public array $ruleChanges = [],
        public array $inviteEmails = [],
        public ?string $description = null,
        public bool $hideOthersTipsBeforeDeadline = false,
        /** WYSIWYG preview from the wizard; regenerated by the handler if null or taken. */
        public ?string $pin = null,
        /** WYSIWYG preview from the wizard; generated by the handler if null. */
        public ?string $shareableLinkToken = null,
    ) {
    }
}
